// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF3qF6AfiNkEJyeb3r9Hpeu9HtxyrKvFs',
    appId: '1:808104424678:web:77fa9412bd72e794893727',
    messagingSenderId: '808104424678',
    projectId: 'navitres-f8e83',
    authDomain: 'navitres-f8e83.firebaseapp.com',
    storageBucket: 'navitres-f8e83.appspot.com',
    measurementId: 'G-PC1SX8ZGHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwKgjsCUvstJD_8KuJfqa68-q6gOIA280',
    appId: '1:808104424678:android:62b10baee5fbcbe9893727',
    messagingSenderId: '808104424678',
    projectId: 'navitres-f8e83',
    storageBucket: 'navitres-f8e83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'Place your key',
    appId: 'Place your key',
    messagingSenderId: 'Place your key',
    projectId: 'Place your key',
    storageBucket: 'Place your key',
    androidClientId: 'Place your key',
    iosClientId: 'Place your key',
    iosBundleId: 'Place your key',
  );
}
